### ISSUE TITLE
Cannot build the unity project

### ISSUE THREAD

**Issue by mengruoshan** [teichgraf/WinMLExperiments#1]
Hi,
When I tried to build the project in unity, it showed like that.

![issue](https://user-images.githubusercontent.com/26344481/41283562-8028a91e-6e69-11e8-95ac-2b1ac98115b0.PNG)
![issue2](https://user-images.githubusercontent.com/26344481/41283563-8087dca4-6e69-11e8-8f2d-f7ef3adc8272.PNG)
I just open your project in unity 2018.1.31f and build it for Universal Windows Platform.
Could you please help me to check if there is anything wrong with my building or is there anything else I need to install in unity?

Thank you very much and hope you have a good day.

**Comment by reneschulte** [comment]
Looks like you are missing the WinML APIs so likely the Windows SDK 17xxx is not installed on your machine. 
See the Readme: 
On your development machine you also need at least Unity 2017 or 2018 and Visual Studio 2017 with the Windows SDK for Build 17xxx / 1803 / April 2018 / RS4 installed.

**Comment by mengruoshan** [comment]
Thank you for your reply.

I have updated my pc to version 1803 and got 10.0.17134.0 in visual studio. For now, I can build a solution from unity but when I try to build the solution in visual studio, it shows like this.

![issue3](https://user-images.githubusercontent.com/26344481/41344456-c73d6b6c-6f33-11e8-955c-b4dc2ab135fe.PNG)
![issue4](https://user-images.githubusercontent.com/26344481/41344460-c9434bfc-6f33-11e8-8ddd-6ee5165b3e8f.PNG)

Could you help me check why is it or I use sdk wrongly?

Thank you very much for your help

**Comment by reneschulte** [comment]
Seems like you are compiling against the wrong .NET SDK. Make sure to use Visual Studio 2017 and the right .NET SDK like defined in the unity player settings. Also try Unity's Build and Run instead of just Build and see if that works.
