### ISSUE TITLE
App crashing on deploy

### ISSUE THREAD

**Issue by progge-sol** [teichgraf/WinMLExperiments#2]
The app crashes when I try to deploy it.

The error occurs in app.cs in line 19
`m_AppCallbacks = new AppCallbacks();`

The output messages are

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in HoloVision18.exe
The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)

Die Aktivierung der Windows Store-App "HoloVision18_awaf3f2xac5x2!App" ist mit Fehler "Die App wurde nicht gestartet" fehlgeschlagen.
Das Programm "[5624] HoloVision18.exe" wurde mit Code 0 (0x0) beendet.
```

I have no idea what other process could use the file (what file ever it is). Even a freshly restarted HoloLens won't run the app.

**Comment by reneschulte** [comment]
Make sure to use latest from this repo and have the HoloLens update RS5 / Build 177xx / 1809 installed:
https://forums.hololens.com/discussion/10696/announcing-the-hololens-rs5-preview

On your development machine you also need at least Unity 2018.2 and Visual Studio 2017 with the Windows SDK for RS5 / Build 177xx / 1809 installed.
