### ISSUE TITLE
Loading the model from storage file

### ISSUE THREAD

**Issue by rondagdag** [teichgraf/WinMLExperiments#3]
Have an issue loading the onnx model from storage file. I can confirm that the file was stored into 'model.bytes' and loaded using LoadModelFromStorageFileAsync, 
after loading, the _model.Description.InputFeatures is null. 
Any ideas?

**Comment by reneschulte** [comment]
Weird. 

Make sure to use latest from this repo where it's loading it via Stream. Check that the ONNX file is using the file extension like my sample and is stored in the Unity project's Resources folder. 

Also ensure to have the HoloLens update RS5 / Build 177xx / 1809 installed:
https://forums.hololens.com/discussion/10696/announcing-the-hololens-rs5-preview

On your development machine you also need at least Unity 2018.2 and Visual Studio 2017 with the Windows SDK for RS5 / Build 177xx / 1809 installed.
