### ISSUE TITLE
Can I use a different object detection model?

### ISSUE THREAD

**Issue by jtrinidad6** [teichgraf/WinMLExperiments#5]
Great work!! 

I was wondering if I could use a different object detection model like YOLO or tiny yolo and have bounding boxes in the camera?

Thank you

**Comment by reneschulte** [comment]
Yes. That is possible with an inverse projection into the space. Would take a bit of effort but surely possible.

**Comment by jtrinidad6** [comment]
That's great, I'm starting to learn all these things and your project is a great starting point for me to explore a more advance approach in this object detection.

If you could point me to topics or some reading that would help me understand and implement that "inverse projection" that would be great. Anyways, thanks!!!

**Comment by reneschulte** [comment]
Sure: https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera

Basically you would get a frame from the HL camera with its camera2world projection matrix. You run the frame to the neural net to get the bounding box where the object is in the frame. Highlight that in the frame and use the projection matrix to reproject the frame into the world.
