### ISSUE TITLE
Replace squeezenet DNN with pose tracking DNN

### ISSUE THREAD

**Issue by cwule** [teichgraf/WinMLExperiments#6]
The example is great and works without problems out of the box, thanks a lot!

I have a question with regards to replacing the small squeezenet with a larger model such as posenet for bodytracking.
I saw that you load the model as a TextAsset, which seems to lead to memory issues for a larger model.
Can this be loaded eg. as a StreamingAsset and do you know how that can be implemented?

**Comment by doughtmw** [comment]
Hi @cwule! The computational resources on the HL1 & 2 are likely not enough to run a larger model on the device. I would suggest trying out a streaming protocol to offload some of the processing to a companion pc.

**Comment by cwule** [comment]
Thanks @doughtmw for the tip. I also looked at the streaming option and Microsoft Research Cambridge showed an [example](https://youtu.be/0Ov2PdlBKE0?t=1426) where they used the streaming option for pose tracking on the Hololens 1. Unfortunately I need an offline solution. Since there are some smaller pose estimation networks available as well that run on mobile devices, I want to try to get it to run on the Hololens (even at a low framerate).

**Comment by reneschulte** [comment]
Sorry. Just saw that question. Sounds doable but also agreeing that it might be too heavy for the HoloLens. On the other hand if you have a mobile one it might work. 

The TextAsset loading is really just a workaround for Unity's weird behavior. I don't recall exactly why but IIRC there was comment in the code I added that explains the reasoning.
It's likely possible with a newer Unity version to load the model the right way. Even better would be to load directly with the UWP stream IO APIs.

**Comment by cwule** [comment]
@reneschulte Thanks for the tip, I will look into the UWP IO APIs. The OpenCV DNN module would also be comfortable to use, but that doesn't work with UWP + ARM64 unfortunately.
