### ISSUE TITLE
Error at Startup

### ISSUE THREAD

**Issue by Hellstormer00** [teichgraf/WinMLExperiments#8]
Hi,
after I deployed the project to my hololens emulator, the emulator showed a green cross and a text saying: "Error Init: Object Reference not set to an instance of an object".

I used the same unity version as you and vs 2019. I deployed on x64 release version

**Comment by reneschulte** [comment]
Hi! You need to have a real HoloLens device. The emulator can't use the camera and also WinML with GPU won't work.

**Comment by nlimmen** [comment]
Hi! Unfurtonately I get the same error, while building to an actual Hololens 2 device using Unity 2019 LTS, VS 2019 and released to ARM64. Is there a way to fix this?

**Comment by nlimmen** [comment]
Hi! In some cases I get same error while releasing to an actual HL device. Do you have maybe have an idea what could be causing this?

I am using Unity 2019 LTS, VS2019 and releasing to ARM64.
